/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.view;

/**
 *
 * @author tharu
 */
import edu.ijse.dto.MemberDto;
import javax.swing.JOptionPane;
import edu.ijse.controller.MemberController;
import edu.ijse.dto.BookDto;
import edu.ijse.controller.BookController;
import edu.ijse.controller.IssueController;
import edu.ijse.dto.IssueDto;
import edu.ijse.controller.IssueController;
import java.text.SimpleDateFormat;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.table.DefaultTableModel;

public class BookReturnView extends javax.swing.JFrame {

private MemberController memberController;
private BookController bookController;
private IssueController issueController;
private JDateChooser jDateChooser;
    /**
     * Creates new form BookReturnView
     */
    
    public BookReturnView() {
        initComponents();
        memberController = new MemberController();
        bookController = new BookController();
        issueController = new IssueController();
        jDateChooser = new JDateChooser();
        connect();
        tablevi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Connection con;
    PreparedStatement pst;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCode1 = new javax.swing.JLabel();
        txtstid = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblsinfo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        lblCode2 = new javax.swing.JLabel();
        keep = new javax.swing.JLabel();
        lblCode4 = new javax.swing.JLabel();
        lblmsg = new javax.swing.JLabel();
        btnret = new javax.swing.JButton();
        lblCode3 = new javax.swing.JLabel();
        isdate = new com.toedter.calendar.JDateChooser();
        lblCode5 = new javax.swing.JLabel();
        irdate = new com.toedter.calendar.JDateChooser();
        lblfee = new javax.swing.JLabel();
        feeview = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        lblCode = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JButton();
        lblbinfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCode1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCode1.setText("St ID :-");

        txtstid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtstid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstidActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(204, 204, 204));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Book Return");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        lblCode2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCode2.setText("Keep Days :- ");

        keep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblCode4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCode4.setText("Additional fee:- ");

        lblmsg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnret.setText("Returned");
        btnret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretActionPerformed(evt);
            }
        });

        lblCode3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCode3.setText("returning date:- ");

        lblCode5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCode5.setText("issued date:- ");

        lblfee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        feeview.setText("View Fee");
        feeview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeviewActionPerformed(evt);
            }
        });

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        lblCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCode.setText("Book ID :-");

        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtstid, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(btnret))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(isdate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCode5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(irdate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCode4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblfee, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(keep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(feeview))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblbinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCode, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblsinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblCode1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtstid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblCode))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblbinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCode3)
                    .addComponent(isdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCode5)
                    .addComponent(irdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblCode2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(feeview))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCode4)
                    .addComponent(lblfee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnret)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtstidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstidActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
      seacrhCustomer();
      loaddata();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
      
    }//GEN-LAST:event_tblMouseClicked

    private void btnretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretActionPerformed
      
      updateitem();
    }//GEN-LAST:event_btnretActionPerformed

    private void feeviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeviewActionPerformed
       returning();
    }//GEN-LAST:event_feeviewActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        searchBook();
    }//GEN-LAST:event_btnSearch1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BookReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BookReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BookReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BookReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BookReturnView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnret;
    private javax.swing.JButton feeview;
    private com.toedter.calendar.JDateChooser irdate;
    private com.toedter.calendar.JDateChooser isdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keep;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblCode1;
    private javax.swing.JLabel lblCode2;
    private javax.swing.JLabel lblCode3;
    private javax.swing.JLabel lblCode4;
    private javax.swing.JLabel lblCode5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblbinfo;
    private javax.swing.JLabel lblfee;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JLabel lblsinfo;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtstid;
    // End of variables declaration//GEN-END:variables
private void seacrhCustomer() {
        try {
            String nic = txtstid.getText();
            MemberDto memberDto = memberController.get(nic);
            if (memberDto != null) {
                lblsinfo.setText(memberDto.getNic() + " | " + memberDto.getName());
            } else {
                JOptionPane.showMessageDialog(this, "Error at Search Student");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error at Search Student");
        }
        
    }
public void connect(){
        
    try { Class.forName("com.mysql.cj.jdbc.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "Vismine@123"); 
    } catch (ClassNotFoundException ex) {
           ex.printStackTrace();
        } catch (SQLException ex) {
             ex.printStackTrace();
        }  
    }
public void tablevi(){
            String columns[]={"NIC","bookid","IssueDate","DueDate","returnStatus"};
            DefaultTableModel dta = new DefaultTableModel(columns,0){
            @Override
            public boolean isCellEditable(int row,int column){
            return false;
            }
            };
            tbl.setModel(dta);
}

    private void loaddata() {
            String columns[]={"NIC","bookid","IssueDate","DueDate","returnStatus"};
            DefaultTableModel dta = new DefaultTableModel(columns,0){
            @Override
            public boolean isCellEditable(int row,int column){
            return false;
            }
            };
            tbl.setModel(dta);
       
            String nic = txtstid.getText();
            String query = "SELECT * FROM issue WHERE NIC = ?";
    try (

            PreparedStatement pstmt = con.prepareStatement(query)) {
            pstmt.setString(1, nic);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                String nicValue = rs.getString("NIC");
                String bookId = rs.getString("bookid");
                String issueDate = rs.getString("issueDate");
                String dueDate = rs.getString("dueDate");
                String returnBook = rs.getString("returnBook");
               dta.addRow(new Object[]{nicValue, bookId, issueDate, dueDate, returnBook});
               
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    } 

    private void returning() {
        SimpleDateFormat dfo = new SimpleDateFormat("dd-MM-yyyy");
        String due = dfo.format(isdate.getDate());
        String issu = dfo.format(irdate.getDate());
        
        Date startDate = irdate.getDate();
        Date endDate = isdate.getDate();

        if (startDate != null && endDate != null) {
            long diffInMillies = Math.abs(endDate.getTime() - startDate.getTime());
            long diffInDays = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);

            keep.setText( diffInDays + " days");
            long keeps = diffInDays;
            if(keeps>14){
            long fee = diffInDays*45;
            lblmsg.setText("You've keep books more than two weeks.You need to pay fines");
            lblfee.setText(fee+"/-  Rupees");
            }else{
            lblfee.setText("No fee to pay");
            lblmsg.setText("You're free to go");
            }
        } else {
            keep.setText("Please select both dates.");
        }
    }
    private void updateitem() {
        
          try {
            IssueDto dto = new IssueDto(txtstid.getText(),txtid.getText(),"vv","cd","Yes");
            String resp = issueController.update(dto);
            JOptionPane.showMessageDialog(this, resp);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at update Item");
        }
  
     }
    private void searchBook() {
    try {
            String bookid = txtid.getText();
            BookDto bookDto = bookController.get(bookid);
            if (bookDto != null) {
                lblbinfo.setText( bookDto.getBtitle());
            } else {
                JOptionPane.showMessageDialog(this, "Error at Search Book");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error at Search Book");
        }
    }
    }


